### ISSUE TITLE
request_manager module

### ISSUE THREAD

**Issue by akahard2dj** [akahard2dj/All-In-One-Estate#8]
when a attemping number is increased (1 to 2), the code is dead.

Error Log
DEBUG: request_c3: http://land.naver.com/article/divisionInfo.nhn?rletTypeCd=A01&tradeTypeCd=&hscpTypeCd=&articleOrderCode=&cortarNo=2914000000 requesting... Requests Error Msg: HTTPConnectionPool(host='land.naver.com', port=80): Max retries exceeded with url: /article/divisionInfo.nhn?rletTypeCd=A01&tradeTypeCd=&hscpTypeCd=&articleOrderCode=&cortarNo=2914000000 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x009A9AD0>, 'Connection to land.naver.com timed out. (connect timeout=10)'))
Retrying to connect ... 2/5

Traceback (most recent call last):
    File "D:/Workspace/PyCharm/All-In-One-Estate/run.py", line 7, in <module>
        apt.request_c3()
    File "D:\Workspace\PyCharm\All-In-One-Estate\estate\estate_main.py", line 171, in request_c3
        self.__request_manager.request('request_c3', url, self.request_c3_callback, idx)
    File "D:\Workspace\PyCharm\All-In-One-Estate\estate\request_manager.py", line 31, in request
        req.close()
UnboundLocalError: local variable 'req' referenced before assignment

**Comment by motal** [comment]
I fixed.
